.flake8, .gitignore, .vscode/settings.json, pre-commit-config.yaml, pyproject.toml, requirements-dev.txt
- 개발 환경 초기 설정 추가
- 코드 스타일 자동화 도구 세팅 (black, isort, flake8)
- vscode code formatting 세팅
- pre-commit 훅 구성 완료
=> chore: Setup development environment(black, isort, flake8, pre-commit)

.pre-commit-config.yaml
=> chore: 숨김파일 설정 변경

tests/code/entire_code.py
- 모델 로드
- 필드별 임베딩 
- 규칙 기반 매칭 스코어 계산 
- 유저 회원가입
- 추천 유저 100명 조회
- enum_converter.py  연동 전
=> feat: 테스트용 전체 코드 추가

tests/code/entire_code.py
- Enum_converter 적용
- 엔드포인트 api 명세랑 동일하게 수정(매칭: tuning, 회원등록: register)
=> feat: Enum_converter 적용 및 엔드포인트 수정

api/v1/controllers/tuning_controller.py, api/v1/controllers/users_post_controller.py, api/v1/endpoints/tuning_router.py, api/v1/endpoints/users_post_router.py, main.py, schemas/user_schema.py
endpoints 모듈 개발을 통해 Swagger 테스트 가능케 함.
- API 엔드포인트 매핑 기능 구현
- 비즈니스로직 미구현으로 인한 임의 응답 추가
- 비즈니스로직 구현시 주석 해제 예정
- v1 기준 미구현 코드 삭제
- main.py 구현(개발환경에서 swagger 접속 가능토록)
=> feat: endpoints 모듈 개발

requirements-dev.txt
FastAPI 서버 개발에 따른 관련 패키지 추가
- FastAPI, Uvicorn
- Pydantic
- python-dotenv
=> chore: FastAPI 관련 패키지 추가

app/api/v1/controllers/users_post_controller.py, app/api/v1/endpoints/tuning_router.py, app/api/v1/endpoints/users_post_router.py, app/core/vector_database.py, app/main.py, app/services/users_post_service.py
- 서비스 연결 완료
- 폴더 구조 변경으로 인한 절대 경로로 수정 
- 내부 확인용  api추가
어떤 변경 사항이 있나요?
=> feature:  서비스 연결 완료

app/utils/error_handler.py, app/utils/logger.py
* 추후 처리시간, 리소스 사용량 등 모니터링을 위한 로깅 추가
* 성능 및 부하 테스트 후 전체적으로 전역 에러 처리를 위한 핸들러 추가
어떤 변경 사항이 있나요?
=> feat: 로깅 및 에러 핸들러 추가

app/tests/integration/test_tuning_flow.py, app/tests/integration/test_user_registration.py, app/tests/units/test_enum_converter.py, app/tests/units/test_tuning.py, app/tests/units/test_users_post.py
각 기능 및 모듈의 정상작동 확인을 위해 단위 테스트 코드 추가
단위 테스트 완료 후 전체 흐름이 정상적으로 작동하는지 확인을 위해 통합 테스트 코드 추가
단위 테스트
- 사용자 데이터 텍스트로 변환(테스트 이상없음)
- 각 필드별 임베딩 생성(테스트 이상없음)
- 빈 필드 있을 경우 임베딩 생성(테스트 이상없음)
- ENUM 변환(테스트 이상없음)
- 매칭 점수 계산(테스트 필요)
통합 테스트
- 남은 테스트(테스트 필요)
- 매칭 추천 리스트(테스트 필요)
어떤 변경 사항이 있나요?
더 필요한 테스트 혹은 불필요한 테스트가 있는지?
=> test: 단위 및 통합테스트 추가

app/api/v1/controllers/users_post_controller.py, app/api/v1/endpoints/users_post_router.py, app/core/embedding.py, app/core/matching_score.py, app/services/users_post_service.py
[유저 등록 코드 리팩토링](https://github.com/100-hours-a-week/2-hertz-ai/issues/28) #28 
[무엇을 수정했는가]
- 사용자 간 매칭 로직 (compute_matching_score)의 유사도 계산 방식을 리팩토링했습니다.
- 
- 기존의 단순 일치/비교 중심의 룰 기반 계산에 더해, 필드별 임베딩 벡터 평균과 코사인 유사도를 결합하도록 개선했습니다.
[왜 수정했는가]
- 보다 정확하고 정성적인 추천을 위해, 관심사 기반의 벡터 유사도와 성향 기반 룰 매칭을 함께 고려하는 방식으로 개선했습니다.
- 필드 누락이나 예외 상황에서도 시스템이 안정적으로 동작하도록 예외 처리 및 기본값 설정을 보완했습니다.
- 하드코딩된 상수값을 구조화된 상수로 추출해 유지보수성과 확장성을 높였습니다.
[어떻게 수정했는가]
- MBTI, ageGroup, preferredPeople 등 핵심 성향 요소에 대해 가중치를 적용한 매칭 점수 함수 분리
- field_embeddings 평균화 및 결합 방식 정리
- cosine_similarity + rule_based_similarity 가중 결합 방식 적용
- 불필요한 하드코딩 및 중복 코드 제거
어떤 변경 사항이 있나요?
=> refactor: 유저등록 코드 리팩토링

app/services/users_post_service.py
#28 #29 
[REGISTER_USER_HTTP_ERROR] {'code': 'EMBEDDING_REGISTER_SERVER_ERROR', 'message': 'Expected ID to be a str, got 13 in get.'} 
입력 값과 기대하는 값의 자료형 불일치로 인한 에러 수정
어떤 변경 사항이 있나요?
=> fix: Pydantic 모델 변환 관련 형식불일치 에러 수정

.gitignore, app/services/users_post_service.py, app/tests/integration/test_tuning_flow.py, app/tests/units/test_tuning.py, app/tests/units/test_users_post.py
서비스 모듈에 대한 단위/통합 테스트 추가
.gitignore에 chroma_db 디렉토리 제외 설정
어떤 변경 사항이 있나요?
정상동작
* units/test_tuning
에러 발생 부분
* units/test_user_post
* /integration/test_user_registration
* /integration/test_tuning_flow
=> test: 단위 및 통합테스트 수정

app/tests/integration/test_tuning_flow.py, app/tests/integration/test_user_registration.py, app/tests/units/test_enum_converter.py, app/tests/units/test_matching_score.py, app/tests/units/test_tuning.py, app/tests/units/test_users_post.py
테스트 코드의 가독성과 유지보수성을 개선하기 위해 포괄적인 주석을 추가했습니다. 
테스트 모듈, 클래스, 함수 그리고 복잡한 로직에 주석을 작성하여 코드의 목적과 동작을 명확히 이해할 수 있도록 했습니다. 
어떤 변경 사항이 있나요?
* 모듈 상단: 전체 모듈의 목적과 주요 기능 요약
* 클래스/함수: 기능, 파라미터, 검증 내용 설명
* 인라인 주석: 복잡한 로직이나 테스트 데이터의 의미 설명
=> docs: 테스트 코드에 상세 주석 추가

app/api/v1/controllers/users_post_controller.py, app/api/v1/endpoints/monitoring_router.py, app/api/v1/endpoints/users_post_router.py, app/core/matching_score.py, app/core/vector_database.py, app/schemas/user_schema.py
어떤 변경 사항이 있나요?
크로마 디비 로컬 환경에서 서버 환경으로 변경 (테스트 시에는 주석 처리된 부분을 살리고 추가된 부분만 주석처리하면 됨)
기존 MBTI 유사도 방식 ->  유사도 방식과 궁합 기반 스코어 계산으로 변경 
연령대 스코어 계산 방식 변경 : 동일하면 1스코어 - 위아래 연령대 0.5 스코어 - 그 외 0 스코어
오타 수정
=> refactor: chromaDB 서버 경로로 변경 및 매칭 스코어 계산 고도화

app/api/v1/endpoints/tuning_router.py, app/core/embedding.py, app/core/matching_score.py, app/main.py, app/services/tuning_service.py, app/services/users_post_service.py, app/utils/logger.py, requirements.txt
logger 기능 코드 구현 
어떤 변경 사항이 있나요?
```
{
"code": "PERFORMANCE_SUMMARY_RETRIEVED",
"data": {
"api_response_times": {
"get_matching_users": {
"count": 2,
"avg": 0.0255,
"min": 0.006,
"max": 0.045,
"p95": 0.045
},
"embed_fields": {
"count": 1,
"avg": 0.364,
"min": 0.364,
"max": 0.364,
"p95": 0.364
},
"compute_matching_score": {
"count": 1,
"avg": 0.013,
"min": 0.013,
"max": 0.013,
"p95": 0.013
},
"register_user": {
"count": 1,
"avg": 0.571,
"min": 0.571,
"max": 0.571,
"p95": 0.571
}
},
"errors": {
"register_user": {
"HTTPException": 1
}
},
"memory_usage": {
"samples": 5,
"avg": 372.165625,
"max": 385.859375,
"current": 385.859375
},
"memory_usage_by_function": {
"embed_fields": {
"count": 1,
"avg": 372.78125,
"max": 372.78125,
"latest": 372.78125
},
"compute_matching_score": {
"count": 1, …
```
=> feat: Logger 기능 추가

app/api/v1/endpoints/health_router.py, app/main.py
#35 
배포된 서버에서 제대로 서버가 연결되었는지 확인하는 API 추가
어떤 변경 사항이 있나요?
: 로컬에서 테스트한 결과이기 때문에 스크린 샷에서는 연결 실패로 뜨는 것이 맞습니다.
=> feat: Health check api 추가

app/api/v1/controllers/tuning_controller.py, app/api/v1/controllers/users_post_controller.py, app/core/matching_score.py, app/core/vector_database.py, app/schemas/user_schema.py, requirements.txt
- MBTI Unkwoun 값들에 대한 스코어 계산 처리 추가
- 튜닝 (매칭 추천) 컨트롤러에 로거 네임 추가
- pydantic 스키마 제약사항 추가
- 
어떤 변경 사항이 있나요?
=> refactor: MBTI Unkwoun 스코어 계산 처리 및 리팩토링

requirements.txt
requirements 버전 수정
어떤 변경 사항이 있나요?
=> chore: requirements 버전 수정

app/core/vector_database.py
로컬에서는 실행이 잘 되나 실제 운영 서버에 올렸을 때 메인 서버가 동작되지 않는 오류가 발생
해당 오류는  vector_database.py 코드에서 실행되는 것으로 추정되어 
오류가 나도 서버 가동에 영향이 없도록 try exception  구문을 사용하여 에러 처리 및 환경변수 이용한 크로마 디비 환경 변경 코드 추가
어떤 변경 사항이 있나요?
```
mode = os.getenv("CHROMA_MODE", "server")  # "local" 또는 "server"
```
추후에 환경변수에 추가하면 됩니다.
서버 모드
```
CHROMA_MODE=server
CHROMA_HOST=localhost
CHROMA_PORT=8001
```
로컬모드
```
CHROMA_MODE=local
```
=> fix:chromaDB로 인한 서버 에러 해결을 위한 코드 수정

app/core/vector_database.py
```
host = host.replace("http://", "").replace("https://", "")
```
현재 설치된 chromadb 버전 (0.4.13) 이상에서는
host에 http://가 들어가면 URL 파싱이 꼬이거나 이중 http:// 문제가 생기게 변경되었을 가능성이 높습니다.
또는 host가 http://localhost:8001이고 port=8001이면 → 결과는 http://http://localhost:8001:8001/... 같은 URL이 되어 망가집니다. 따라서 위와 같이 수정합니다.
어떤 변경 사항이 있나요?
=> fix: ChromaDB  서버 연결 에러 이슈로 인한 host 경로 수정

app/services/users_post_service.py
```
from app.core.vector_database import get_similarity_collection, get_user_collection
```
즉, user_collection이 None인데 .get(...)을 호출해서 에러가 난 것입니다.
기존 collection에 직접 접근하는 방법을 피하고 위와 같이 우회함수를 사용하여 에러를 수정하였습니다. 
어떤 변경 사항이 있나요?
=> fix: ChromaDB 우회 함수로 호출 수정

.gitignore, app/tests/load_tests/config.py, app/tests/load_tests/monitoring/chroma_metrics.py, app/tests/load_tests/monitoring/metrics_collector.py, app/tests/load_tests/monitoring/visualizer.py, app/tests/load_tests/run_load_test.py, app/tests/load_tests/runners.py, app/tests/load_tests/scaling_test.py, app/tests/load_tests/scenarios/embedding_scenarios.py, app/tests/load_tests/scenarios/tuning_scenarios.py
서비스의 부하가 걸리는 지점을 파악하고 추후 최적화에 활용하기 위해  프레임워크를 구현하고 초기 테스트를 수행
사용자 등록 부분에 주요 연산이 몰려있다보니 이에 대한 확인으로 처리시간, 리소스 사용량 등을 모니터링함
구현한 부하 테스트 기능:
- 사용자 등록 부하 테스트 (임베딩 생성 및 유사도 계산)
- 매칭 추천 부하 테스트 (기존 유사도 기반 추천)
- 시스템 자원 사용량 모니터링 (CPU, 메모리, 디스크 I/O)
- 테스트 결과 분석 및 시각화
어떤 변경 사항이 있나요?
>테스트 결과 요약
평균 응답 시간: 0.608초
처리 속도: 3.15 req/sec
CPU 사용률: 평균 25.68%, 최대 41.3%
메모리 사용률: 평균 76.8%, 최대 79.7%
평균 응답 시간: 1.506초
처리 속도: 3.22 req/sec
CPU 사용률: 평균 12.6%, 최대 19.0%
메모리 사용률: 평균 75.58%, 최대 78.8%
평균 응답 시간: 0.038초
처리 속도: 125 req/sec
CPU 사용률: 평균 0.0%, 최대 0.0%
메모리 사용률: 평균 71.7%, 최대 71.7%
대규모 테스트 시 메모리 사용량이 비교적 높은 편입니다. 임베딩 모델 최적화를 고려할 필요 있음
유사도 계산 부분의 복잡도에 비해 사용자 증가에 따른 성능 저하가 예상보다 적었음
더 큰 규모(500~1000명)에서도 이러한 추세가 유지되는지 추가 테스트 필요
=> test: 부하 테스트 코드 추가

app/services/tuning_service.py, app/services/users_post_service.py, app/utils/logger.py
---
HTTPException의 에러 메시지 형식이 누락된 함수에서  `"code"` 및 `"message"` 혹은 `"data"` 구조로 통일하여 API 에러 응답 형식을 명확히 했습니다.  
또한, `update_similarity_for_users` 함수에 `@log_performance` 데코레이터를 수정하여 성능 및 메모리 측정이 가능하도록 개선했습니다.  
그 외에도 JSON 파싱 오류나 메타데이터 유효성 검증 등을 통해 안정성을 높였습니다.
---
어떤 변경 사항이 있나요?
---
- 에러 메시지 구조 변경:  
예:  
```python
raise HTTPException(
status_code=404,
detail={
"code": "TUNING_NOT_FOUND_USER",
"data": None
}
)
---
* `userId` 추출이 잘 되도록 `log_performance` 데코레이터 내부에 `hasattr(arg, "userId")`를 추가했으며, 성능 로그에서 누락되던 값이 이제 잘 기록됩니다.
* 예외 메시지 구조를 전반적으로 통일하였는데, 기존 클라이언트 파싱 코드에 영향이 없는지 확인 부탁드립니다.
* 함수별 로깅 적용을 더 확대하는 것도 고려 중인데, 이에 대한 의견도 환영합니다.
---
=> refactor: 에러 반환 메세지 수정 및 로거 누락 값 추가

app/core/matching_score_optimized.py
매칭 알고리즘의 성능과 확장성을 개선하기 위한 최적화 작업을 수행
사용자가 많아질수록 속도가 느려지는 문제와 메모리 효율성 문제를 해결하기 위해 벡터화된 계산 방식 적용 및 사용자 필터링 로직 개선
어떤 변경 사항이 있나요?
=> feat: 매칭 알고리즘 성능 최적화 및 코드 개선

.gitignore, app/tests/performance/generate_report.py, app/tests/performance/performance_test.py, app/tests/performance/run_all.py
매칭 알고리즘의 성능 최적화 효과를 정량적으로 측정하고 분석할 수 있는 테스트 시스템 구현
실행 시간, 메모리 사용량, 매칭 품질 등 다양한 측면에서 알고리즘 성능을 측정하고, 그 결과를 시각화하여 보고서 생성 기능 추가
테스트 결과인 txt, csv 등 .gitignore에 추가
어떤 변경 사항이 있나요?
- [ㅌ] 새로운 기능 추가
<html><head></head><body><h1>매칭 알고리즘 성능 개선 결과 보고서</h1>
<p><em>생성 일시: 2025-05-09 14:51:03</em></p>
<h2>1. 실행 시간 비교</h2>
<p><strong>최대 속도 향상:</strong> 1.20배 (사용자 수: 500명)<br>
<strong>평균 속도 향상:</strong> 0.95배</p>
<h3>사용자 수별 실행 시간 (초)</h3>
사용자 수 | 기존 코드 | 개선 코드 | 속도 향상
-- | -- | -- | --
10 | 0.0058 | 0.0363 | 0.16
50 | 0.0165 | 0.0145 | 1.13
100 | 0.0729 | 0.0624 | 1.17
500 | 0.3405 | 0.2846 | 1.20
1000 | 0.6785 | 0.6249 | 1.09
<h2 class="text-xl font-bold text-text-100 mt-1 -mb-0.5" level="2">2. 매칭 품질 비교</h2>
<p class="whitespace-pre-wrap break-words"><strong>Jaccard 유사도 평균:</strong> 1.0000<br>
<strong>순위 …
=> test: 매칭 알고리즘 최적화 성능 비교 테스트 및 보고서 생성 기능 추가

app/core/matching_score_optimized.py, app/services/users_post_service.py
매칭 점수 계산 로직을 성능이 최적화된 새 버전으로 교체
`users_post_service.py`에서 기존 로직에서 최적화된 로직으로 모듈 교체함에 따라 계산 소요 감소 기대
어떤 변경 사항이 있나요?
=> refactor: 매칭 점수 계산 로직을 최적화된 버전으로 교체

app/api/v1/endpoints/monitoring_router.py
#47
코드 리뷰를 통한 불필요한 코드 삭제`async** def` -> `def` 
이유: 
- DB 조회, 파일 접근, 네트워크 요청 없음
- 단순히 기록된 로그 정보를 Python 객체로 정리해서 반환
어떤 변경 사항이 있나요?
- [] 문서 또는 관련 설정을 수정했습니다. (필요 시)
=> chore: 불필요한 코드 삭제

app/services/tuning_service.py
부하 테스트 기반으로 튜닝 리스트 API는 단순 조회 및 반환인데 생각보다 응답 속도가 느리다는 것을 깨달았다. 
(이후에 알게된 점은 부하테스트 시, 등록되지 않은 아이디 값들로 요청을 할 경우, 예외 처리 경로를 거치기 때문에 응답속도가 늘어나는 편임)
그래도 코드를 뜯어가면서 다시 필요한 점과 불필요한 점을 신중하게 고민하면서 개선할 수 있어서 보람있었다.
어떤 변경 사항이 있나요?
<html><head></head><body>
항목 | 개선 전 | 개선 후 | 차이점 요약
-- | -- | -- | --
✅ 총 요청 수 | 300 | 500 | 테스트 지속 시간 늘림 (더 많은 부하 감내 확인 가능)
✅ 성공률 (200/404) | 71% (213건) | 75.4% (377건) | ✔ 성공률 향상 (예외 처리 or 안정성 개선으로 추정)
❌ 실패률 | 28.99% | 24.6% | ✔ 에러 4.3% 감소
⏱ 평균 응답 시간 (avg) | 721.92ms | 39.16ms | 🚀 20배 이상 개선!!
🔁 처리 속도 (req/s) | 28.56 req/s | 47.31 req/s | ✔ 요청 처리 속도 대폭 향상
⌛ 최대 응답 시간 (max) | 4.21s | 270ms | ✔ 최악의 케이스도 90% 이상 단축
📦 데이터 수신량 | 61 KB | 102 KB | ✔ 더 많은 결과 전송 → 정상 처리 증가 의미
🧠 메모리 & 처리 비용 | 높음 (응답 지연, 실패 반복) | 낮음 (빠른 응답) | ✔ 개선된 코드 로직 효율성 입증
</body></html>
불필요한 코드를 삭제하고 단순화 했습니다.
PR이 …
=> refactor: 매칭 리스트 속도 향상을 위한 리팩터링

app/api/v2/controllers/tuning_report_controller.py, app/api/v2/endpoints/tuning_report_router.py, app/core/prompt_templates/tuning_report_prompt.py, app/main.py, app/models/qwen_loader.py, app/schemas/tuning_schema.py, app/services/tuning_report_service.py
#55
- Colab GPU 환경을 이용하여 모델을 가동하고 이를 vscode에서 활용할 수 있도록 환경을 구축하였습니다. 
- 설계 3단계에서 작성했던 아키텍쳐 반영하여 폴더 구조를 생성하였습니다
- 모델은 선정 가능성이 높은 Qwen3로 테스트한 코드를 활용할 수 있도록 올렸습니다. 
어떤 변경 사항이 있나요?
```
INFO:     211.244.225.211:0 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
INFO:     211.244.225.211:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 05-15 06:58:56 [loggers.py:111] Engine 000: Avg prompt throughput: 78.7 tokens/s, Avg generation throughput: 4.5 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.1%, Prefix cache hit rate: 61.5%
INFO:     211.244.225.211:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 05-15 06:59:06 [loggers.py:111] Engine 000: Avg prompt throughput: 78.7 tokens/s, Avg generation throughput: 4.5 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV …
```
=> feat: 튜닝 리포트 모델 로드 및 모델 적용 코드 추가

app/api/v1/controllers/tuning_controller.py, app/schemas/user_schema.py, app/services/tuning_service.py
튜닝 리스트 요청과 반환 시에 사용되는 스키마를 수정하고 적용하였습니다.
어떤 변경 사항이 있나요?
=> refactor: Response, Request 스키마 수정 적용

app/api/v2/endpoints/tuning_report_router.py
#60
테스트용으로 추가했던 'GPU 확인 API' 라우터를 삭제합니다.
어떤 변경 사항이 있나요?
=> chore: 테스트용 라우터 삭제(#60)

.github/workflows/discord-pr-merged-notify.yml
x
- DEV 브랜치에 PR 요청 후 merge 시에만 디스코드 알림
어떤 변경 사항이 있나요?
- 직접 merge 하여 테스트 해야하므로 merge 우선 진행합니다.
=> "feat: 디스코드 알림 actions 스크립트 추가(PR시 알림)"

.github/workflows/discord-pr-merged-notify.yml
x
디스코드로 가는 데이터의 JSON 형식 오류 수정
어떤 변경 사항이 있나요?
=> fix: 디스코드로 가는 데이터의 JSON 형식 오류 수정

app/models/qwen_loader.py
#66 #56 
- message로 받는 형식을  prompt로 수정
- vllm 호출 경로 변경
- payload  stop  값 변경
어떤 변경 사항이 있나요?
=> fix: 호출되는 vllm API 수정 및 프롬프트 형식 변경

.github/workflows/ci-ai.yml
[Sprint #4 - CL ] - CI/CD 구축
[#163](https://github.com/100-hours-a-week/2-hertz-wiki/issues/163)
들여쓰기 수정
어떤 변경 사항이 있나요?
=> feat:ai ci 적용 테스트

.github/workflows/ci-ai.yml
PR 웹훅 추가, uvicorn requirements에서 설치
어떤 변경 사항이 있나요?
=> fix: PR 웹훅 추가, uvicorn requirements에서 설치

app/core/vector_database.py
도커 환경에서 ChromaDB를 재시작할 경우, FastAPI가 이전의 끊긴 Chroma 클라이언트와 컬렉션 객체를 재사용하면서 500 Internal Server Error가 발생하는 문제가 있었습니다.
이 문제를 해결하기 위해:
- `get_chroma_client()` 함수에 헬스 체크(`list_collections()`)를 추가하여 죽은 연결을 감지하고 재연결할 수 있도록 수정했습니다.
- `get_user_collection()` 및 `get_similarity_collection()`에 컬렉션 객체 유효성 검사 로직 추가
- `.get()`을 사용하는 함수들에 예외 처리를 적용하여 불완전한 응답이나 연결 실패에 안전하게 대응
어떤 변경 사항이 있나요?
=> fix: ChromaDB 연결 불안정 이슈 대응 및 컬렉션 객체 유효성 검사 추가

app/core/vector_database.py
=> fix:환경 변수 변경

.github/workflows/cd-ai.yml
[Sprint #4 - CL ] - CI/CD 구축
[#163](https://github.com/100-hours-a-week/2-hertz-wiki/issues/163)
ai-cd 코드 추가 하여 CI/CD 구축
어떤 변경 사항이 있나요?
=> feature: cd 코드 추가

.github/workflows/cd-ai.yml
실행되지 않아서 브렌치 지정하는 코드도 추가
어떤 변경 사항이 있나요?
=> fix: 브랜치 지정

app/core/vector_database.py
변경사항으로 이슈 해결되지 않아 롤백
어떤 변경 사항이 있나요?
=> revert: ChromaDB 클라이언트 유효성 검사 로직 수정

.github/workflows/cd-ai.yml
ci 완료 후 배포가 트리거가 작동하도록 수정
어떤 변경 사항이 있나요?
=> fix: 트리거 수정

app/core/vector_database.py
아직 테스트 안했다고 해서 ChromaDB 유효성 검사 로직 구현 코드 롤백
어떤 변경 사항이 있나요?
=> fix:ChromaDB 유효성 검사 로직 롤백

.github/workflows/cd-ai.yml
=> fix: ai-ci 로 수정

.github/workflows/cd-ai.yml
[Sprint https://github.com/100-hours-a-week/2-hertz-ai/pull/4 - CL ] - CI/CD 구축 https://github.com/100-hours-a-week/2-hertz-wiki/issues/163
dispatch 수동 배포추가 
어떤 변경 사항이 있나요?
=> feat: dispatch 추가

.github/workflows/cd-ai.yml
main 롤백 로직의 주석을 해제
어떤 변경 사항이 있나요?
=> fix: 롤백 주석 해제

.github/workflows/cd-ai.yml
=> fix: env 수정

.github/workflows/cd-ai.yml
=> hotfix: 타겟 브렌치로 브렌치 값을 가져오도록 변경

.github/workflows/ci-ai.yml, .github/workflows/deploy_workflow-ai.yml
=> feat: ci/cd 통합

.github/workflows/deploy_workflow-ai.yml
=> hotfix: 헬스체크 3회 시도로 변경

.gitignore, app-tuning/requirements-dev.txt, app-tuning/requirements.txt
.gitignore에서 모든 .txt 파일을 제외하도록 설정했지만, 이로 인해 프로젝트에서 필요한 requirements.txt와 requirements-dev.txt 파일도 함께 무시되는 문제가 발생했습니다. 
이를 해결하기 위해 .gitignore에 예외 규칙을 추가하여 필요한 의존성 파일은 올바르게 Git에서 추적되도록 수정했습니다.
어떤 변경 사항이 있나요?
=> fix: .gitignore 수정으로 requirements.txt 파일 추적

.github/workflows/deploy-tuning.yml
기존 app -> app-tuning으로 변경함에 따라 ci/cd 코드를 변경하였습니다.
어떤 변경 사항이 있나요?
=> fix: ai-tuning으로 변경

app-tuning/utils/logger.py
#112
- logger를 통해 user_id 값과 함께 로그를 기록하는데, 특정 함수에서는 unknown 으로 뜸
- async_wrapper 과 sync_wrapper 동시 수정
어떤 변경 사항이 있나요?
=> [#112]fix: logger에서 누락된 user_id 값 추가를 위한 수정

app-tuning/api/endpoints/user_router.py, app-tuning/core/vector_database.py, app-tuning/main.py, app-tuning/services/user_service.py
#111
제품 트러블 슈팅 후, 백엔드DB와 동기화 위한 유저 삭제  API  리팩토링
어떤 변경 사항이 있나요?
=> [#111]refactor: 유저 삭제 API 코드리팩토링

app-report/models/qwen_loader_gcp.py, app-report/services/tuning_report_service_gcp.py
#55 
* GCP VM 환경에서 직접 GPU를 활용하여 튜닝 리포트를 생성할 수 있도록 모델 추론 로직을 개선
* 기존의 Colab/Ngrok과 별개로 GCP 서버에서 GPU를 직접 사용하는 방식으로 변경
* GCP 서버의 GPU에서 Qwen 모델을 직접 로드하고 추론하는 방식으로 변경
* 모델 예열 로직 추가로 첫 요청 시 지연 시간 감소
* 응답 파싱 로직 강화 및 오류 처리 개선으로 서비스 안정성 향상
* 메모리 효율성을 위한 모델 로딩 파라미터 최적화
* 외부 서비스(Colab/Ngrok) 의존성으로 인한 불안정성 제거
* 테스트 안정성 향상 필요
어떤 변경 사항이 있나요?
* Ngrok-Colab 테스트 환경도 현재는 유지할 계획이므로 테스트 환경에 따라 변경 소요 존재
* 단, 동일한 레포를 통해 로컬 및 GCP 상에서 테스트 가능
* 단순 테스트 목적으로 GCP 테스트용에서는 Qwen2.5 사용 중
* 추후 vLLM 프레임워크 적용시 수정 예정
=> feat: GCP 상에서 GPU 기반 Qwen 모델 추론 로직 구현

app-tuning/scripts/get_metadata_by_id.py
메타데이터만 확인하는 스크립트를 작성하였습니다.
이는 백엔드DB에는 취향등록이 정상적으로 저장되지 않아서 
AI 운영 서버에서  등록된 사용자들의 취향 정보를 확인하고자 개발하였습니다.
어떤 변경 사항이 있나요?
`app-tuning/script` 폴더 생성하여 하위에 스크립트 파일 생성하였습니다.
`python scripts/get_metadata_by_id.py 11` 로 확인합니다. 
=> feat: 메타데이터 확인용 스크립트 추가

app-tuning/api/controllers/user_controller.py
reponse에서 data를 한 번 더 감싸서 반환되어 기존의 반환 스키마와 맞지 않아 수정
어떤 변경 사항이 있나요?
=> feat:사용자 삭제 응답 메시지 형식 수정

.github/workflows/deploy-tuning.yml, .github/workflows/docker-deploy-tuning.yml
DISCORD_WEBHOOK_CICD_URL 수정
어떤 변경 사항이 있나요?
=> fix: DISCORD_WEBHOOK_CICD_URL 수정

app-report/langchain-mcp-adapters/client.py, app-report/langchain-mcp-adapters/introduce.py, app-report/langchain-mcp-adapters/langchain_client_ollama.py, app-report/langchain-mcp-adapters/langchain_client_vllm.py, app-report/langchain-mcp-adapters/weather_server.py
#57 
LangChain과 MCP(Model Context Protocol)를 활용한 다중 서버 에이전트 시스템 구현
LangChain-MCP-Adapters 라이브러리를 통해 최초 선정한 요구사항들을 충족할 수 있는지 테스트함
주요 테스트 사항:
* MCP 클라이언트를 통한 다중 서버 연결 및 도구 통합
* 개인 정보 조회 서비스 (나이, 직업, 취미)
* 실시간 날씨 정보 서비스
* Ollama와 vLLM 모델 지원
어떤 변경 사항이 있나요?
> Ollama + 로컬 컴퓨터 상 응답 결과(qwen2.5:3b)
```
질문을 입력하세요: julia의 취미는?
답변: The hobby of julia is doing nothing.
질문을 입력하세요:  Julia의 취미는?
답변: Julia的爱好是瑜伽。
질문을 입력하세요: 서울의 날씨는?
답변: 현재 서울의 날씨는 다음과 같습니다: ☀️ +24°C 입니다.
질문을 입력하세요:  Ethan의 직업이 뭔지 알려줘
답변: Ethan의 직업은 DevOps Engineer입니다.
질문을 입력하세요:  Fiona와 Diana 중 누가 더 나이가 많 은지 비교해줘
답변: Based on the information provided by the age function, Fiona is 38 years old and Diana is 31 years old. Therefore, Fiona is older than Diana.
```
* 내용 측면에서는 원하는 답변이 출력됨
* 단, 영어와 중국어로 답변하는 경우가 많음
> vLLM + 로컬 컴퓨터 상 응답 …
=> test: langchain-mcp-adapters 구현 테스트

app-report/mcp-test/client.py, app-report/mcp-test/local_llm_client.py, app-report/mcp-test/local_llm_server.py, app-report/mcp-test/math_server.py, app-report/mcp-test/multi_client.py, app-report/mcp-test/server.py, app-report/mcp-test/weather_server.py
#57 
MCP(Model Context Protocol)에 대한 전반적인 테스트를 위해 서버-클라이언트 통신 시스템을 구현했습니다. 
다양한 도구(파일 시스템 조작, 수학 연산, 날씨 정보)를 제공하는 MCP 서버들과 이를 활용하는 클라이언트를 개발하여 LLM과 외부 도구 간의 표준화된 통신을 가능하게 했습니다.
주요 구현 내용:
* FastMCP를 이용한 다양한 서버 구현 (파일 시스템, 수학, 날씨)
* LangChain과 MCP 어댑터를 통한 멀티 서버 연동
* Hugging Face 모델과 MCP 도구의 통합
어떤 변경 사항이 있나요?
```
app-report/mcp-test/
├── my_client.py          # FastMCP 클라이언트 (비동기)
├── client.py             # Llama 모델과 MCP 서버 통합
├── local_llm_server.py   # 파일 시스템 도구 서버 (ls, cat, echo)
├── math_server.py        # 수학 연산 서버 (add, multiply)
├── server.py             # 구성 가능한 FastMCP 서버
└── weather_server.py     # 날씨 정보 서버
```
- `/mcp-test/client.py`, `server.py`
> 응답 결과
```
mcp = FastMCP(
FastMCP 서버 객체가 생성되었습니다.
도구 'greet'와 'add'가 추가되었습니다.
리소스 'data://config'가 추가되었습니다.
리소스 템플릿 …
```
=> test: mcp 초기 테스트

.gitignore, app-report/config/mcp_config.json, app-report/langchain-mcp-adapters/mcp_config.json, app-report/models/qwen_loader_gcp_vllm.py, app-report/services/tuning_report_service_gcp.py, app-report/services/tuning_report_service_gcp_mcp.py
#57 
GCP 상에서 튜닝 리포트 생성 기능에 MCP 도입 시도 중
MCP(Model Context Protocol) 클라이언트를 활용하여 LangGraph의 ReAct 에이전트와 Qwen2-7B-Instruct 모델 연동 
사용자 정보를 기반으로 튜닝 리포트를 자동 생성하는 기능 제공
주요 구현 내용:
* MCP 설정 파일 로딩 및 서버 설정 생성 기능
* gitignore에서 mcp_config 파일 예외처리
* vLLM을 사용한 Qwen2-7B-Instruct 모델 로더 구현
* ReAct 에이전트를 통한 튜닝 리포트 생성 API 개발
* 모델 예열 및 효율적인 메모리 사용을 위한 최적화
어떤 변경 사항이 있나요?
* 모델 로드 중 VRAM 부족 문제 해결 중
=> feat: v2 API MCP 적용

.github/workflows/docker-deploy-tuning.yml, docker-compose.yml
[TroubleShooting - CL] - chromadb 마이그레이션
[#197](https://github.com/100-hours-a-week/2-hertz-wiki/issues/197)
chromadb를 마이그레이션하고 도커 컴포즈로 관리하는 코드를 추가하고 CI/CD 변경점을 반영하였습니다.
어떤 변경 사항이 있나요?
=> feat: chromadb 마이그레이션

app-report/models/qwen_loader_gcp_ollama.py, app-report/services/tuning_report_service_gcp_mcp.py
사용자 매칭 시 자동으로 뉴스형식의 튜닝 리포트를 생성하는 AI 기능을 구현 
MCP 클라이언트와 Qwen2.5:3b 모델을 연동하여 매칭된 두 사용자 정보를 바탕으로 리포트를 생성
LangGraph의 React Agent를 활용해 워크플로우 구성 및 안정적인 JSON 응답 파싱과 오류 처리 수행
어떤 변경 사항이 있나요?
```
{
"code": "TUNING_REPORT_SUCCESS",
"data": {
"title": " breakout! #ISTJvsENFP 매칭 호기심 유발 - 블루스uit 와 쿨한 펫카즈",
"content": "Hey there, @UserB! 🌟👀 [UserA]이 [UserB]와 연결되었어요! 😁👀 비밀은 공개할게요. 두 사람의 MBTI 조합에 대해 흥미로운 해석이 있습니다! #ISTJvsENFP 매칭! 🤔🧐 UserA는 INTROVERTED, DOESNT_SWEAR, PASSIONATE한 성향으로 알려져 있고, UserB는 NICE, CUTE인 성향을 가지고 있어요. 이 조합은 '블루스uit 와 쿨한 펫카즈'를 상상해보세요! 💃🕺 #ISTJvsENFP 매칭에서 빠질 수 없겠네요! 🤭💕 이제 두 사람의 대화 횟수는 어떻게 될까? 5회차까지 가면 UserA가 '사랑에 빠졌을 확률'은 70%로 뜨거워요! 💕👌 #ISTJvsENFP 매칭 호기심 유발, 그동안의 대화를 통해 얻어진 정보들을 이용해 어떤 결론이 나올지 궁금하나? 🤔🤔 @UserA와 함께 새로운 세계를 열어보세요! Stay Tuned! 💥 #ISTJvsENFP 매칭 호기심 유발!"
}
}
```
* 컨텐츠 결과가 …
=> feat: 튜닝 리포트 생성 및 Ollama 모델 통합 구현

app-tuning/api/controllers/tuning_controller.py, app-tuning/api/controllers/user_controller.py, app-tuning/api/endpoints/tuning_router.py, app-tuning/api/endpoints/user_router.py, app-tuning/main.py, app-tuning/schemas/tuning_schema.py, app-tuning/services/user_service.py, app-tuning/utils/logger.py
Closes #156  
Closes #159  
Closes #163  
Closes #164  
Closes #165  
Closes #166
이번 PR은 코드 리뷰에서 지적된 응답 스키마, 타입 일치, 명명 규칙 개선 사항들을 반영하고, 이를 바탕으로 리팩토링을 병행한 변경입니다.
주요 변경 내용은 다음과 같습니다:
- BaseResponse, TuningResponse 등 응답 스키마를 명시적으로 적용해 반환 타입 일치 (#166)
- 컨트롤러 함수 시그니처 상에서 라우터와 불일치했던 타입(str ↔ int) 을 통일 (#165, #163)
- snake_case 명명 규칙 및 쿼리 파라미터 alias 적용 (#159)
- 응답 구조와 API 문서 예시 간 불일치를 해결하고, Pydantic 모델 기반으로 일관된 응답 보장 (#164)
- 클래스명과 파일명이 불일치했던 부분을 일관되게 변경 (#156)
이 PR을 통해 API 레이어에서 명시적인 응답 구조, 타입 안정성, 네이밍 통일성을 확보했습니다.
어떤 변경 사항이 있나요?
커밋 로그 상에서 (#156), (#165) 등은 각 코드 리뷰 피드백을 기반으로 리팩토링된 내역이며, 실제로 해당 이슈 번호와 매핑됩니다.
- 일부 컨트롤러 함수에서 기존에는 dict를 반환하던 부분을 ` BaseResponse(...)` 객체로 변경했습니다.
이 변경은 응답 구조의 일관성을 높이기 위한 것이며, 기존 API와 호환성 문제는 발생하지 않도록 검토했습니다.
- 기존 FastAPI 문서에 나타나던 응답 구조가 모호했던 문제점도 함께 해결되었습니다.
**리뷰 시 …
=> refactor: 응답 스키마 및 컨트롤러 시그니처 일관성 개선 및 관련 코드 정리 (#156, #159, #163, #164, #165, #166)

app-tuning/services/tuning_service.py
#169
변수명이 추상적이라 혼동될 수 있다는 피드백을 반영하여, 코드 가독성과 유지보수성을 높이기 위해 변수명을 명확하게 리네이밍했습니다.
- `sim_data` → `user_similarities`: DB에서 조회한 사용자 유사도 원본 데이터를 명확히 표현
- `sim_map` → `similarity_map`: JSON 파싱된 유사도 딕셔너리임을 드러냄
이러한 변경을 통해 변수명만으로도 구조와 역할이 명확히 전달되도록 개선하였으며, 이후 협업 및 유지보수 시 혼선을 줄일 수 있을 것으로 기대됩니다.
어떤 변경 사항이 있나요?
네이밍 관점에서 더 나은 제안이 있다면 편하게 코멘트 부탁드립니다.
=> refactor: 변수명 명확화를 위한 이름 변경 (#169)

app-report/api/controllers/tuning_report_controller.py, app-report/api/endpoints/tuning_report_router.py, app-report/core/prompt_templates/tuning_report_prompt.py, app-report/main.py, app-report/services/tuning_report_service_gcp_mcp.py, app-report/utils/error_handler.py
Closes #158 
Closes #161 
Closes #162 
Closes #173
1. 모듈 경로를 상대경로로 통일함으로써 프로젝트 환경에 대한 독립성 부여
2. load_dotenv() 함수 호출을 프로세스 당 1번으로 수정
3. MCP 설정 파일 경로를 프로젝트 환경에 독립적이게 설정
4. router-services 연결
5. 미사용 라우터 코드 제거
어떤 변경 사항이 있나요?
=> refactor: 모듈 경로 수정 및 미사용 코드 제거

app-report/api/controllers/tuning_report_controller.py, app-report/api/endpoints/tuning_report_router.py, app-report/models/qwen_loader_gcp_ollama.py, app-report/requirements.txt
close #179
TuningReportService 호출 시 발생하는 인스턴스화 오류
+ v2 API 서버 구축을 위한 requirements.txt 추가
어떤 변경 사항이 있나요?
주요 수정 사항:
* TuningReportController에서 클래스 메서드 호출을 인스턴스 메서드 호출로 변경하여 "missing positional argument" 오류 해결
* create_tuning_report 함수에서 불필요한 self 매개변수 제거
* 모델 로드 스크립트에서 ollama:qwen - 7b로 수정
=> fix: TuningReportService 인스턴스 호출 및 requirements 추가

.github/workflows/deploy-report.yml
[Sprint #5 - CL] - GPU 서버 구축
[#273](https://github.com/100-hours-a-week/2-hertz-wiki/issues/273)
- GPU 서버 구축
- CI/CD 구축
어떤 변경 사항이 있나요?
=> feat: tuning-report CI/CD 구축

.github/workflows/deploy-report.yml
[Sprint #5 - CL] - GPU 서버 구축
[#273](https://github.com/100-hours-a-week/2-hertz-wiki/issues/273)
서버가 실행중이 아니라면 CD가 작동하지 않도록 수정
어떤 변경 사항이 있나요?
=> fix: 서버가 실행중인지 확인

app-report/services/tuning_report_service_gcp_mcp_prod.py
Closes #185  
* MCP 도구 호출 임시로 연결 해제
어떤 변경 사항이 있나요?
=> fix: MCP 도구 호출시 빈 응답 반환 이슈 해결

app-report/test/ollama-vllm-comparison/ollama_concurrent_test.py, app-report/test/ollama-vllm-comparison/ollama_test.py, app-report/test/ollama-vllm-comparison/vllm_concurrent_test.py, app-report/test/ollama-vllm-comparison/vllm_test.py
Closes #194 
Closes #203 
- Qwen2.5-7B 모델의 최적 추론 환경 선정을 위한 Ollama vs vLLM 성능 비교 분석 수행
- 동일 모델에 대해 서로 다른 양자화 방식(Q4_K_M vs AWQ)과 서빙 프레임워크 비교
- 응답 시간, 처리량, 메모리 사용량, 동시 요청 처리 능력에 대한 정량적 벤치마크 결과 도출
- (팀 Wiki 문서화) ChatGPT와 Claude를 활용한 교차 평가를 통해 출력 품질의 객관적 평가 수행
- (팀 Wiki 문서화) 사용 목적별 최적 프레임워크 선택 가이드라인 제시
어떤 변경 사항이 있나요?
지표 | Ollama (Q4_K_M) | vLLM (AWQ)
-- | -- | --
평균 응답시간 | 7.58초 | 4.84초
응답시간 범위 | 7.04~8.13초 | 3.42~6.60초
출력 토큰 수 | 174~216 token | 161~200 token
평균 초당 처리 토큰 | 25.8 token/s | 39.6 token/s
VRAM 사용량 | 5,353MB | 20,898MB
지표 | Ollama (Q4_K_M) | vLLM (AWQ)
-- | -- | --
전체 처리시간 | 9.55초 | 5.74초
평균 응답시간 | 7.09초 | 4.87초
평균 초당 처리 토큰 | 12.6 token/s | 17.4 token/s
VRAM 사용량 | 5,353MB | 20,898MB
ChatGPT: Ollama가 저널리즘 객관성 측면에서 우수
Claude: vLLM이 기술적 정확성과 구조적 완성도에서 우수
=> feat: Ollama/vLLM 단일/동시 요청에 대한 성능 비교 평가

.github/workflows/deploy-report.yml
- vllm 서버 분리로 인한 헬스체크 시간 연장
어떤 변경 사항이 있나요?
=> fix: tuning-report hc 시간 연장

.github/workflows/docker-deploy-tuning.yml
- main에도 트리거가 되도록 수정
- 수동 배포 추가
main에도 트리거 되도록 변경
어떤 변경 사항이 있나요?
=> fix: tuning main에도 적용

.github/workflows/docker-deploy-tuning.yml
Hotfix/tuning api main
어떤 변경 사항이 있나요?
=> hotfix: tuning-api 로 변경

app-chat-report/api/controllers/chat_report_controller.py, app-chat-report/api/endpoints/chat_report_router.py, app-chat-report/models/hyper_clover_loader.py, app-chat-report/models/kcelectra_base_loader.py, app-chat-report/schemas/chat_report_schema.py, app-chat-report/services/chat_report_service.py, app-chat-report/utils/error_handler.py, app-chat-report/utils/logger.py
#227 
- logger.warning() 관련 오류 수정 (logger import 방식 수정)
- 중복 핸들러 등록 방지를 위한 로거 설정 로직 리팩터링
- API 응답 에러 포맷을 명확히 정의 및 표준화 (format_error_response 활용)
- 422, 400, 404, 500 등의 에러 반환 형식 명세화 및 일관성 부여
어떤 변경 사항이 있나요?
추가적으로 필요한 에러 형식이나 에러 핸들러가 있다면 편하게 말씀해주세요.
=> feat: 로그 구체화 및 반환 형식 정의(#227)

app-chat-report/db/mongodb.py, app-chat-report/services/chat_report_service.py
#227 
채팅 메시지 유해성 검사 로직을 리팩토링하여 코드의 가독성과 유지보수성을 개선했습니다. (#227)
- 단일 책임 원칙 적용: 룰베이스 검사, AI 모델 분석, DB 저장 로직을 별도 함수로 분리
- 설정 관리 개선: 하드코딩된 값들을 ToxicityConfig 클래스로 중앙 관리
- 데이터 구조화: ToxicityResult 데이터클래스로 결과 데이터 표준화
- 중복 코드 제거: 공통 로직(create_report_document, create_response)을 재사용 가능한 함수로 분리
어떤 변경 사항이 있나요?
>함수 분리 구조: 각 함수의 단일 책임 원칙 적용이 적절한지 확인해주세요
> 룰베이스 검사에서 단순 문자열 포함 검사(if profanity in message)를 사용하는데, 단어 경계 검사나 더 정교한 매칭 로직이 필요한지 검토해주세요.
=> feat: 룰베이스 필터링 적용

app-chat-report/db/mongodb.py, app-chat-report/requirements.txt, app-chat-report/scripts/populate_filters.py, app-chat-report/services/chat_report_service.py
#227 
동적으로 규칙 기반 필터링 단어를 관리하기 위하여 MongoDB에 필터링할 단어들을 등록하고,
이를 참조하여 필터링할 수 있도록 코드를 구현
word(단어), is_active(적용 상태), updated_at(최근 업데이트 날짜), created_at(최초 등록일) 로 상태 관리
비동기 DB Driver 설치
어떤 변경 사항이 있나요?
- 캐시 TTL 시간(현재 5분)이 적절한지 검토 부탁드립니다
- 필터 단어 추가/삭제 API 구현 여부에 대한 의견 부탁드립니다
- 정규표현식 패턴 자동 감지 로직의 정확성 검토 부탁드립니다
=> feat:룰베이스필터 mongoDB연동 추가

app-report/test/multi-agent/poc_supervisor_agent.py, app-report/test/multi-agent/simple_test_tavily.py, app-report/test/multi-agent/validate_tool_use_tavily.py
#247 
- LangGraph를 활용한 에이전트 구조를 검증하기 위한 테스트 스크립트 추가
1. Supervisor Agent 구조 검증: 여러 전문 에이전트 각각에게 역할을 부여하고 조율하는 Supervisor 구조가 정상적으로 동작하는지 확인
2. 도구 사용(Tool-Use) 신뢰성 검증: 에이전트가 외부 도구(Tavily 웹 검색)를 환각 없이 안정적으로 호출하고 그 결과를 활용하는지 테스트
어떤 변경 사항이 있나요?
=> feat: LangGraph supervisor 및 tool 사용 에이전트 테스트 스크립트 추가

app-report/test/multi-agent/async_tool_wrapper.py, app-report/test/multi-agent/tuning_report_service_with_supervisor.py
#231 
#247
- Supervisor 에이전트가 여러 전문 에이전트에게 작업을 동적으로 위임하는 새로운 멀티 에이전트 파이프라인 도입
- 각 에이전트(관계 분석, 주제 기획, 검색 등)의 역할을 명확히 분리하고, 전체 워크플로우를 총괄하는 Supervisor가 이들을 순차적으로 호출하여 최종 튜닝 리포트 생성 
- TavilySearch 도구와 AsyncToolWrapper 유틸리티를 구현하여 agent 구조에서 도구 호출이 가능토록 함
어떤 변경 사항이 있나요?
| 생성 예시
```json
{"title": "이 날은 음악과 파스타를 즐기는 두 사람의 특별한 데이트!", "content": "카스 매치와 활동 계획:\n- 카스 매치: 김지훈과 박서연, 음악과 파스타의 완벽한 파트너\n- 활동 계획:\n  - 음악의 밤: 침착한 카페에서 편안한 대화를 나눈 후, 뮤직 페스티벌로 이동하여 현장의 음악 분위기를 느끼게 한다.\n  - 맛있는 여행: 두 가지 다른 레스토랑을 방문한다. 하나는 맛있는 파스타로 유명하고, 다른 하나는 다양한 요리를 제공한다.\n  - 공동 경험: 아트 미술관이나 야외 콘서트 같은 활동을 선택하여, 서로의 취향이 어떻게 조화를 이루는지 보여준다.\n취미를 위한 작은 놀이:\n- 놀이 1: 뮤직 페스티벌에서 상대방에게 특별히 준비한 노래를 선보이며, 서로의 사랑을 표현한다.\n- 놀이 2: 카페에서 상대방에게 특별히 준비한 아침 차를 제공하며, 그녀가 좋아하는 파스타를 포함한다.\n결론:\n- 결론: 이번 데이트는 우리의 공통된 취향을 만족시키는 동시에, 서로를 더 잘 이해하게 …
```
=> test: supervisor 기반 멀티 에이전트 리포트 생성 파이프라인 테스트

app-report/models/exaone_loader_gcp_vllm.py, app-report/models/midm_loader_gcp_transformer.py
#247 
#250 
- 한국어 언어 모델에 대한 적용 테스트
- 멀티에이전트를 통해 여러 단계로 나눠 역할 분담을 한 만큼 이전 단계의 결과물이 이후 결과에 영향을 미침
- 재시도 로직이 아닌 한국어 특화 모델로 서빙 모델을 교체함으로써 생성 안정성을 높이고자 함
어떤 변경 사항이 있나요?
=> test: exaone, midm 등 한국어 언어 모델 테스트

app-report/test/llm_judge/llm_evaluate_test_dataset.py
#247 
- LLM 평가자를 활용해 튜닝리포트의 품질을 자동으로 측정하는 평가 파이프라인을 구축하고 테스트함
- 변경된 평가지표인 '헤드라인 주목도', '본문 재미', '가독성', '컨셉 완성도' 4가지 핵심 지표와 상세 척도가이드가 포함된 정교한 프롬프트를 사용하여 LLM(Gemini)에 평가를 요청
- 정규표현식을 통해 LLM의 구조화된 텍스트 응답에서 각 항목별 점수를 자동으로 파싱 및 정량화
- 이를 통해 사람에 의한 수동 평가에 소요되는 시간과 노력을 절감하고, 모델 성능 개선을 위한 객관적이고 일관된 데이터 기반 마련
어떤 변경 사항이 있나요?
=> test: LLM 기반 콘텐츠 자동 평가 파이프라인 구현 및 테스트

.github/workflows/docker-deploy-chat-report.yml, Dockerfile.base-chat-report, Dockerfile.chat-report, app-chat-report/requirements-prod.txt, app-chat-report/requirements.txt
신고 API 서버 CI/CD 구축
어떤 변경 사항이 있나요?
=> feat: chat-report CI/CD 구축

.github/workflows/docker-deploy-tuning.yml
모델 명 환경변수화 하여 동적으로 CI/CD에 삽입
어떤 변경 사항이 있나요?
=> fix: AI 모델 명 환경변수화

app-report/api/controllers/tuning_report_controller.py, app-report/models/midm_loader_gcp_vllm.py, app-report/services/tuning_report_service_gcp_prod.py
#260 
- 기존에 FastAPI 애플리케이션 시작 시, 프로세스 내에서 직접 무거운 LLM을 로드하여 발생하던 VRAM 부족(Out of Memory) 오류를 해결하기 위해 양자화된 모델을 서빙
- 이를 통해 애플리케이션의 메모리 사용량을 최소화하고 초기 모델 로드 시간을 단축했으며, 동기적인 모델 추론으로 인해 발생하던 이벤트 루프 블로킹 문제 해결
어떤 변경 사항이 있나요?
| 생성결과
```json
{
"code": "TUNING_REPORT_SUCCESS",
"data": {
"title": "🚨[감정폭발] ISTJxENFP, 같은 취미 다른 우주! 디저트 아트 vs 즉흥 낙서 대전쟁🔥",
"content": "아, 이거 진짜 꿀잼 각이다! MBTI 궁합 중에서도 이 조합만큼 드라마틱한 게 또 있을까? ISTJ와 ENFP가 함께 그림을 그린다는 건 마치 엑셀과 즉석카메라가 만나서 벌이는 환상의 파티랄까? 🎉\n\n**1단계: \"계획부터 세워야지\" vs \"일단 그려보자!\"**\n\nISTJ가 스케치북을 펼치자마자 눈에서 레이저 빔 발사! \"우선 구도 잡고, 비율 맞추고, 컬러 팔레트부터 정해야겠어.\"라고 중얼거리는 순간, ENFP는 벌써 붓을 휘두르며 \"야, 그냥 느낌대로 가는 거지! 인생 뭐 있어, 일단 그리는 거야!\"라고 외친다. 이 시점에서 둘의 거리는 약 5만 광년 정도 떨어져 있다고 보면 된다. \n\nISTJ: (자를 들고 정확한 각도 체크하며) \"여기서 3mm만 더 나가면 황금비율이 깨지는데...\"\nENFP: (붓으로 휘리릭) \"에이, 그런 거 신경 쓰지 마! …
```
=> refactor: 모델 로딩 방식을 vLLM 클라이언트-서버 구조로 변경 및 양자화 모델 적용

app-tuning/services/user_service.py
=> hotfix: float32 초과 방지 - 버그 수정

app-tuning/core/matching_score_by_category.py, app-tuning/requirements.txt, app-tuning/scripts/recompute_all_similarities_optimized.py, app-tuning/services/user_service.py
=> hotfix: 유사도 계산 오류 버그 수정

app-tuning/requirements-base.txt
pandas 라이브러리 설치 추가
어떤 변경 사항이 있나요?
=> docs: pandas 라이브러리 설치 추가

.github/workflows/docker-deploy-tuning.yml
Hotfix: 헬스체크 시간 증가
어떤 변경 사항이 있나요?
=> Hotfix: 헬스체크 시간 증가

app-tuning/scripts/recompute_all_similarities_optimized.py, app-tuning/services/user_service.py
=> feat: 유사도 계산 직렬화

.github/workflows/docker-deploy-chat-report.yml
CI/CD 시 가져오는 SSM 파라미터 변경
어떤 변경 사항이 있나요?
=> refactor: chat-report SSM 파라미터 경로 변경

.github/workflows/docker-deploy-tuning.yml, app-tuning/main.py, docker-compose.yml
- cpu 수직 확장으로 docker-compose, workflow 변경
- 서버 최초 실행 시 작동하는 스크립트 주석 처리
어떤 변경 사항이 있나요?
=> Refactor: Prod 서버 CPU 수직 확장에 의한 마이그레이션
